fix: restored yarn install logic

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,7 +18,17 @@ yarn_auth: &yarn_auth
 
 npm_dependency_installation: &npm_dependency_installation
   name: Installing NPM dependencies
-  command: yarn install --verbose
+  command: |
+    attempts=0
+    until [ $attempts -ge 5 ]
+    do
+        yarn install --frozen-lockfile && break
+        attempts=$[$attempts+1]
+        echo "yarn install attempt $attempts failed, retrying"
+    done
+    if [ $attempts -ge 5 ]; then
+        exit 5
+    fi
 
 dependency_cache_key: &dependency_cache_key dependency-cache-{{ checksum "yarn.lock" }}
 
